language: r
r:
  - devel
  - release
  - oldrel

cache: packages

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libgdal-dev

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
